import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar"
import Navbar from "@/components/Navbar";
import AuthProvider from "@/context/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider >

          <div className="flex min-h-screen w-full">
            <AppSidebar />
            <main className="flex-1">
              <Navbar />
              {/* <SidebarTrigger /> */}
              {children}
              <Toaster richColors />
            </main>

          </div>
        </SidebarProvider>

      </body>
      </AuthProvider>
    </html>
  );
}
